Test if workflows will fail

diff --git a/.github/workflows/issue-modification-to-pr-update.yml b/.github/workflows/issue-modification-to-pr-update.yml
--- a/.github/workflows/issue-modification-to-pr-update.yml
+++ b/.github/workflows/issue-modification-to-pr-update.yml
@@ -9,7 +9,7 @@ jobs:
   convert-issue-to-pr:
     runs-on: ubuntu-latest
     env:
-      BACKEND_URL: https://api.staging.allocator.tech
+      BACKEND_URL: https://api.staging.allocator
     steps:
       - name: Check out code
         uses: actions/checkout@v2
@@ -18,7 +18,14 @@ jobs:
         run: |
           REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
           echo "Updating PR from Issue: ${{ github.event.issue.number }} in $REPO_NAME"
-          curl --header "Content-Type: application/json" \
+          RESPONSE=$(curl --header "Content-Type: application/json" \
                --request POST \
                --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
-               "${BACKEND_URL}/application/update-from-issue"
+               "${BACKEND_URL}/application/update-from-issue")
+
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Failed to upadate from issue.. HTTP response code: $RESPONSE"
+            exit 1
+          else
+            echo "Issue successfully updated."
+          fi
diff --git a/.github/workflows/issue-to-pr.yml b/.github/workflows/issue-to-pr.yml
--- a/.github/workflows/issue-to-pr.yml
+++ b/.github/workflows/issue-to-pr.yml
@@ -9,7 +9,7 @@ jobs:
   convert-issue-to-pr:
     runs-on: ubuntu-latest
     env:
-      BACKEND_URL: https://api.staging.allocator.tech
+      BACKEND_URL: https://api.staging.allocator
     steps:
       - name: Check out code
         uses: actions/checkout@v2
@@ -19,7 +19,15 @@ jobs:
           REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
           echo "Converting Issue To PR with repo: $REPO_NAME"
           echo "Issue number: ${{ github.event.issue.number }}"
-          curl --header "Content-Type: application/json" \
-               --request POST \
-               --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
-               "${BACKEND_URL}/application"
+          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+            --header "Content-Type: application/json" \
+            --request POST \
+            --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
+            "${BACKEND_URL}/application")
+
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Failed to convert issue to PR. HTTP response code: $RESPONSE"
+            exit 1
+          else
+            echo "Issue successfully converted to PR."
+          fi
diff --git a/.github/workflows/renew-application-cache.yml b/.github/workflows/renew-application-cache.yml
--- a/.github/workflows/renew-application-cache.yml
+++ b/.github/workflows/renew-application-cache.yml
@@ -10,11 +10,18 @@ jobs:
   renew_cache:
     runs-on: ubuntu-latest
     env:
-      BACKEND_URL: https://api.staging.allocator.tech
+      BACKEND_URL: https://api.staging.allocator
     steps:
       - name: Renew Application Cache
         run: |
           REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
-          curl -X POST "${BACKEND_URL}/application/cache/renewal" \
+          RESPONSE=$(curl -X POST "${BACKEND_URL}/application/cache/renewal" \
           -H "Content-Type: application/json" \
-          -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}'
+          -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}')
+
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Failed to renew cache. HTTP response code: $RESPONSE"
+            exit 1
+          else
+            echo "$RESPONSE"
+          fi
