Fix CI

diff --git a/.github/workflows/renew-application-cache.yml b/.github/workflows/renew-application-cache.yml
--- a/.github/workflows/renew-application-cache.yml
+++ b/.github/workflows/renew-application-cache.yml
@@ -14,7 +14,14 @@ jobs:
     steps:
       - name: Renew Application Cache
         run: |
-          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
-          curl -X POST "${BACKEND_URL}/application/cache/renewa" \
+          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -X POST "${BACKEND_URL}/application/cache/renewal" \
           -H "Content-Type: application/json" \
-          -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}'
+          -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}')
+
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Failed to renew cache. HTTP response code: $RESPONSE"
+            exit 1
+          else
+            echo "$RESPONSE"
+          fi
