Test

diff --git a/.github/workflows/renew-application-cache.yml b/.github/workflows/renew-application-cache.yml
--- a/.github/workflows/renew-application-cache.yml
+++ b/.github/workflows/renew-application-cache.yml
@@ -18,3 +18,10 @@ jobs:
           curl -X POST "${BACKEND_URL}/application/cache/renewa" \
           -H "Content-Type: application/json" \
           -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}'
+
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Failed to renew cache. HTTP response code: $RESPONSE"
+            exit 1
+          else
+            echo "$RESPONSE"
+          fi
